# Generated by Django 5.2 on 2025-04-14 10:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('character_class', models.CharField(choices=[('Berserker', 'Berserker'), ('Paladin', 'Paladin'), ('Gunlancer', 'Gunlancer'), ('Destroyer', 'Destroyer'), ('Striker', 'Striker'), ('Wardancer', 'Wardancer'), ('Scrapper', 'Scrapper'), ('Soulfist', 'Soulfist'), ('Gunslinger', 'Gunslinger'), ('Artillerist', 'Artillerist'), ('Deadeye', 'Deadeye'), ('Sharpshooter', 'Sharpshooter'), ('Bard', 'Bard'), ('Sorceress', 'Sorceress'), ('Shadowhunter', 'Shadowhunter'), ('Deathblade', 'Deathblade'), ('Reaper', 'Reaper'), ('Summoner', 'Summoner'), ('Arcana', 'Arcana'), ('Artist', 'Artist'), ('Aeromancer', 'Aeromancer'), ('Slayer', 'Slayer')], max_length=20)),
                ('item_level', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('roster_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(300)])),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_main', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
