# Generated by Django 5.1.8 on 2025-04-14 12:40

import django.db.models.deletion
import lost_ark.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('gold_amount', models.PositiveIntegerField()),
                ('cooldown_weeks', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Valtan', 'Valtan'), ('Vykas', 'Vykas'), ('Kakul-Saydon', 'Kakul-Saydon'), ('Brelshaza', 'Brelshaza'), ('Akkan', 'Akkan'), ('Thaemine', 'Thaemine'), ('Echidna (Act 1)', 'Echidna (Act 1)'), ('Brelshaza (Act 2)', 'Brelshaza (Act 2)'), ('Kazeros (Act 3)', 'Kazeros (Act 3)'), ('Kayangel', 'Kayangel'), ('Ivory Tower', 'Ivory Tower'), ('Behemoth', 'Behemoth')], max_length=100)),
                ('difficulty', models.CharField(choices=[('Normal', 'Normal'), ('Hard', 'Hard'), ('Hell', 'Hell')], max_length=10)),
                ('min_ilvl', models.PositiveIntegerField()),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='is_gold_earner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(choices=[('Berserker', 'Berserker'), ('Paladin', 'Paladin'), ('Gunlancer', 'Gunlancer'), ('Destroyer', 'Destroyer'), ('Striker', 'Striker'), ('Wardancer', 'Wardancer'), ('Scrapper', 'Scrapper'), ('Soulfist', 'Soulfist'), ('Gunslinger', 'Gunslinger'), ('Artillerist', 'Artillerist'), ('Deadeye', 'Deadeye'), ('Sharpshooter', 'Sharpshooter'), ('Bard', 'Bard'), ('Sorceress', 'Sorceress'), ('Shadowhunter', 'Shadowhunter'), ('Deathblade', 'Deathblade'), ('Reaper', 'Reaper'), ('Summoner', 'Summoner'), ('Arcana', 'Arcana'), ('Artist', 'Artist'), ('Aeromancer', 'Aeromancer'), ('Slayer', 'Slayer'), ('Machinist', 'Machinist'), ('Glavier', 'Glavier'), ('Wild Soul', 'Wild Soul')], max_length=20),
        ),
        migrations.CreateModel(
            name='CharacterWeeklyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(default=lost_ark.models.get_current_week)),
                ('status', models.CharField(default='Not Done', max_length=20)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_contents', to='lost_ark.character')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateField(auto_now_add=True)),
                ('character_weekly_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_gate_entries', to='lost_ark.characterweeklycontent')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_ark.gate')),
            ],
            options={
                'unique_together': {('character_weekly_content', 'gate')},
            },
        ),
        migrations.AddField(
            model_name='characterweeklycontent',
            name='completed_gates',
            field=models.ManyToManyField(blank=True, through='lost_ark.CompletedGate', to='lost_ark.gate'),
        ),
        migrations.AddField(
            model_name='gate',
            name='weekly_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='lost_ark.weeklycontent'),
        ),
        migrations.AddField(
            model_name='characterweeklycontent',
            name='weekly_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_ark.weeklycontent'),
        ),
        migrations.AlterUniqueTogether(
            name='gate',
            unique_together={('weekly_content', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='characterweeklycontent',
            unique_together={('character', 'weekly_content', 'week')},
        ),
    ]
