# Generated by Django 5.1.8 on 2025-04-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark', '0002_gate_weeklycontent_character_is_gold_earner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterweeklycontent',
            name='status',
            field=models.CharField(choices=[('Not Done', 'Not Done'), ('Gate 2', 'Gate 2'), ('Gate 3', 'Gate 3'), ('Gate 4', 'Gate 4'), ('Completed', 'Completed')], default='Not Done', max_length=20),
        ),
    ]
