# Generated by Django 5.1.8 on 2025-04-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark', '0003_alter_characterweeklycontent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklycontent',
            name='name',
            field=models.CharField(choices=[('Thaemine', 'Thaemine'), ('Echidna', 'Echidna'), ('Behemoth', 'Behemoth'), ('Aegir (Act 1)', 'Aegir (Act 1)'), ('Brelshaza (Act 2)', 'Brelshaza (Act 2)'), ('Kazeros (Act 3)', 'Kazeros (Act 3)')], max_length=100),
        ),
    ]
