# Generated by Django 5.1.8 on 2025-04-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark', '0004_alter_weeklycontent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterweeklycontent',
            name='status',
            field=models.CharField(choices=[('not_done', 'Not Done'), ('gate_2', 'Gate 2'), ('gate_3', 'Gate 3'), ('gate_4', 'Gate 4'), ('completed', 'Completed')], default='Not Done', max_length=20),
        ),
    ]
