# Generated by Django 5.1.8 on 2025-04-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark', '0005_alter_characterweeklycontent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterweeklycontent',
            name='status',
            field=models.CharField(choices=[('Not Done', 'Not Done'), ('Gate 2', 'Gate 2'), ('Gate 3', 'Gate 3'), ('Gate 4', 'Gate 4'), ('Completed', 'Completed')], default='Not Done', max_length=20),
        ),
    ]
